### PR TITLE
Tree.Diff

### PR DESCRIPTION
**Pull request by zwilias**
CC @stoeffel @jxxcarlson as you both expressed interest in this!

### CODE REVIEW

**Comment by jxxcarlson** [comment]
# Using Tree.Diff

In the examples below, I use the `jxxcarlson/htree` library to 
to construct trees from indented outlines. In the first example,
the trees are of type `Tree String`.  In the second, they are of type
`Tree Annotated String`, where 

```
type alias AnnotatedString = ((Int, Int), String)
```

This type is what I am thinking of using to optimize rendering
of math text in `jxxcarlson/elm-markdown`, a pure elm Markdown
library that can render TeX/LaTeX-style math formulas using
MathJax 3.  One things of an annotated string as being 
`((version, id), content)`,  where `version` is an integer that is 
incremented on each edit, `id` is a unique identifier for each block
of Markdown text (computed by a parser), and `content` is, well, contant.
The idea is to signal MathJax to re-render content whenever the pair 
`(version, id)` changes.  Then it will re-render only nodes that
have changed rather than all of them.  (I have to use keyed nodes to make
sure that things get re-rendered;  at the moment, the whole document is 
single keyed node -- not good for documents with a lot of math.


## Example 1

### Text

**Original text**

```
text1 =
    """
Intro
Data Structures
  Lists
  Trees
Algorithms
  Brute-force
  Binary search
  Probabalistic
"""
```

**Edited text**

```
text2 =
    """
Introduction
Data Structures
  Lists
  Trees
  Queues
Algorithms
  Brute-force
  Binary search
""
```
### Trees

```
> tree1 = HTree.String.parse text1
Tree "*" [
   Tree "Intro" []
 , Tree ("Data Structures") [Tree "Lists" [],Tree "Trees" []]
 , Tree "Algorithms" [Tree "Brute-force" []'
     ,Tree ("Binary search") [],Tree "Probabalistic" []]]
```

```
> tree2 = HTree.String.parse text2
   Tree "*" [
      Tree "Introduction" []
    , Tree ("Data Structures") [Tree "Lists" []
    , Tree "Trees" [],Tree "Queues" []]
    , Tree "Algorithms" [Tree "Brute-force" []
        ,Tree ("Binary search") []]]
```

### Diff
```
> Diff.diff (==) tree1 tree2
   Patch (Copy "*" [
      Patch (Replace (Tree "Intro" []) (Tree "Introduction" []))
    , Patch (Copy ("Data Structures") [
         Keep (Tree "Lists" [])
       , Keep (Tree "Trees" [])
       , Patch (Insert (Tree "Queues" []))])
    , Patch (Copy "Algorithms" [Keep (Tree "Brute-force" [])
       , Keep (Tree ("Binary search") [])
       , Patch (Delete (Tree "Probabalistic" []))])])
```

## Example 2

Same texts as before, but this time the trees will be of type
`Tree AnnotatedString`, as noted above.  Let

```
indexer : Int -> Int -> String -> ((Int, Int), String)
indexer version idx str = ((version, idx), str)
```

We use this function in conjunction with `Tree.indexedMap` to 
contstruct the trees.

```
> tree1 = HTree.String.parse text1 |> Tree.indexedMap (indexer 2)
  Tree      ((2,0),"*") [
     Tree   ((2,1),"Intro") []
    ,Tree   ((2,2),"Data Structures") [
       Tree ((2,3),"Lists") []
      ,Tree ((2,4),"Trees") []
     ]
    ,Tree   ((2,5),"Algorithms") [
       Tree ((2,6),"Brute-force") []
      ,Tree ((2,7),"Binary search") []
      ,Tree ((2,8),"Probabalistic") []]]
```

```
> tree2 = HTree.String.parse text2 |> Tree.indexedMap (indexer 3)
   Tree        ((3,0),"*") [
       Tree    ((3,1),"Introduction") []
     , Tree    ((3,2),"Data Structures") [
          Tree ((3,3),"Lists") []
        , Tree ((3,4),"Trees") []
        , Tree ((3,5),"Queues") []]
     , Tree    ((3,6),"Algorithms") [
          Tree ((3,7),"Brute-force") []
         ,Tree ((3,8),"Binary search") []]]
```

For equality use

```
equalData : AnnotatedString -> AnnotatedString -> Bool
equalData ((v1, idx1), content1) ((v12, idx2), content2) = (content1 == content2)
```

Then we have

```
> Diff.diff equalData tree1 tree2
   Patch (Copy ((2,0),"*") [
       Patch (Replace (Tree ((2,1),"Intro") []) (Tree ((3,1),"Introduction") []))
     , Patch (Copy ((2,2),"Data Structures") [
           Keep (Tree ((2,3),"Lists") [])
         , Keep (Tree ((2,4),"Trees") [])
         , Patch (Insert (Tree ((3,5),"Queues") []))])
     , Patch (Copy ((2,5),"Algorithms") [
           Keep (Tree ((2,6),"Brute-force") [])
         , Keep (Tree ((2,7),"Binary search") [])
         , Patch (Delete (Tree ((2,8),"Probabalistic") []))])])
```

### Tree after reconciliation

```
> tree3 = HTree.String.parse text2 |> Tree.indexedMap (indexer 3)
   Tree        ((2,0),"*") [
       Tree    ((3,1),"Introduction") []    -- Changed
     , Tree    ((2,2),"Data Structures") [
          Tree ((2,2),"Lists") []
        , Tree ((2,4),"Trees") []
        , Tree ((3,5),"Queues") []]         -- Inserted
     , Tree    ((2,5),"Algorithms") [
          Tree ((2,6),"Brute-force") []
         ,Tree ((2,7),"Binary search") []]]
```

Note that the content part of tree 3 (project `((i,j), content)` to `content`)
is that same as that of tree2, the edited version of tree1.  However, the 
`(version, id)` pair has changed for elements whose content has changed.

**Comment by jxxcarlson** [comment]
Here is an incomplete version of `merge`.  I am still scratching my head about what to do with the `Delete` case.

```

merge : Diff a -> Tree a
merge data =
    case data of
        Keep t ->
            t

        Patch p ->
            patch p


patch : Patch a -> Tree a
patch p =
    case p of
        Insert t ->
            t

        -- Below: BAD, haven't figured out what to do
        Delete t ->
            t

        Replace a b ->
            b

        Copy x list ->
            Tree.tree x (List.map merge list)
```

**Comment by zwilias** [comment]
Yeah, `Delete _` and `Insert _` don't really make sense in the root-position of a `Diff` between two trees. It's something that really bothers me. It only really makes sense in a `List Tree -> List Tree -> List Diff` sort of thing where we're dealing with forests.

I'm going to ponder on this a bit:
- Between the lines, I see a suggestion that passing `a -> a -> Bool` can often be better expressed by passing an `a -> b` where regular equality is used on the `b`. In your case, something like `diffBy Tuple.second`
- I'm also kind of intrigued by the `merge` or `conciliate` or whatever suggestion! On one hand, it makes sense that, having a diff, we could somehow apply it. On the other hand, perhaps we don't need to! We could basically have `conciliateBy : (a -> b) -> Tree a -> Tree a -> Tree a`, which wouldn't even have to bother with building up a `Diff`

I'm going to experiment a bit! Thanks so much for the input, this is invaluable!

**Comment by jxxcarlson** [comment]
Looking forward to your next iteration.

**Comment by jxxcarlson** [comment]
I think that `a -> b` would work in my real case.  Here is what I was using to test that case:

```
type alias Id = (Int, Int)

type MDBlock
    = MDBlock Id BlockType Level BlockContent

equal : MDBlock -> MDBlock -> Bool
equal (MDBlock _ bt1 l1 c1) (MDBlock _ bt2 l2 c2) =
    bt1 == bt2 && l1 == l2 && c1 == c2
```

So one could do 

```
type SimplerBlock = MDBlock BlockType Level BlockContent

simplify : MDBlock -> SimplerBlock
simplify (MDBlock id blockType level blockContent) = 
  (SimplerBlock blockType level blockContent)
```

Would there be any performance difference in `a -> b` versus `a -> a -> Bool`?  My `equal` above is a conjunction of three tests, which is perhaps not as efficient as (==) on the projected values.  But then there is the cost of projection/`simplify`.  Dunno.

**Comment by zwilias** [comment]
Okay, managed to get rid of `Insert`/`Delete` by realizing that those could only appear at the end of a `Copy`. This suggested simplifying a little further, so now we have a `Diff` and `Tail` where a `Tail` signifies the trailing elements for lists of childnodes that don't happen to be the same length.

```elm
type Diff a
    = Keep (Tree a)
    | Replace (Tree a) (Tree a)
    | Copy a (List (Diff a)) (Tail a)

type Tail a
    = Left (List (Tree a))
    | Right (List (Tree a))
    | Empty
```

I also expanded the API slighty, adding `diffBy`, `mergeBy` and `mergeWith`.

> Would there be any performance difference in a -> b versus a -> a -> Bool? My equal above is a conjunction of three tests, which is perhaps not as efficient as (==) on the projected values. But then there is the cost of projection/simplify. Dunno.

I'd guess the `a -> a -> Bool` version would be slightly more performant in your case. Destructuring is cheap and `&&` is "lazy", whereas projection would always need to happen fully _and_ construct new objects.

**Comment by jxxcarlson** [comment]
Very nice!  I tested mergeBy on my example. It worked fine. I’ll try benchmarking some real examples in the next few days.

**Comment by jxxcarlson** [comment]
I tested `Diff.mergeWith equal tree1 tree2` using Markdown source text and the parser which converts it into a tree of blocks.  


**Some benchmarks:**
1. Text of 6800 character => Tree of depth 3 with 79 nodes: processing time 0.5 milliseconds/
2. Test of 13600 character => Tree of depth 3 with 159 nodes, processing time 0.9 milleseconds/tree.

**Comment by zwilias** [comment]
[Released in 1.5.0](https://package.elm-lang.org/packages/zwilias/elm-rosetree/1.5.0/Tree-Diff) 🎉

**Pull request merged**
